# JPA(DB ??) ??
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpabook
    username: inung
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true # JPA? ?? ??? ID ?? ?? ??
    properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # ?? ??

# ?? ??
logging:
  level:
    org:
      hibernate: debug
